openapi: 3.0.0
info:
  title: Menschliche Kommunikationsschnittstelle
  version: 1.3.0
paths:
  /interactions:
    $ref: './paths.yaml#/InteractionsPath'
components:
  schemas:
    InteractionRequest:
      $ref: './components.yaml#/schemas/InteractionRequest'
    Filters:
      $ref: './components.yaml#/schemas/Filters'
    InteractionResponse:
      $ref: './components.yaml#/schemas/InteractionResponse'
    InteractionCreatedResponse:
      $ref: './components.yaml#/schemas/InteractionCreatedResponse'
