openapi: 3.0.2
info:
  version: '1.3.0'
  title: Menschliche Kommunikationsschnittstelle

servers:
  - url: 'http://example.com/api/v1'
  - url: 'https://example.com/api/v1'

tags:
  - name: Kommunikation
    description: Menschliche Kommunikation

paths:
  /interactions:
    $ref: './paths.yaml#/InteractionsPath'

components:
  schemas:
    InteractionRequest:
      $ref: './components.yaml#/schemas/InteractionRequest'
    Filters:
      $ref: './components.yaml#/schemas/Filters'
    InteractionResponse:
      $ref: './components.yaml#/schemas/InteractionResponse'
    InteractionCreatedResponse:
      $ref: './components.yaml#/schemas/InteractionCreatedResponse'
