openapi: 3.0.2
info:
  version: '1.3.0'
  title: Menschliche Kommunikationsschnittstelle

servers:
  - url: 'https://example.com/api/v1'

tags:
  - name: Kommunikation
    description: Menschliche Kommunikation
  - name: Information
    description: Informationen übergeben

paths:
  /interactions:
    $ref: './paths.yaml#/InteractionsPath'
  /informations:
    $ref: './paths.yaml#/InformationsPath'

components:
  schemas:
    InteractionRequest:
      $ref: './components.yaml#/schemas/InteractionRequest'
    Filters:
      $ref: './components.yaml#/schemas/Filters'
    InteractionResponse:
      $ref: './components.yaml#/schemas/InteractionResponse'
    InteractionCreatedResponse:
      $ref: './components.yaml#/schemas/InteractionCreatedResponse'
    InformationRequest:
      $ref: './components.yaml#/schemas/InformationRequest'
    DetailedInformationResponse:
      $ref: './components.yaml#/schemas/DetailedInformationResponse'